
@url = http://127.0.0.1:8080
@api_key = {{$dotenv API_KEY}}

### POST
POST {{url}}/pastebin?api_key={{api_key}}
Content-Type: application/json

{ "type": "str", "val": "I pasted this." }


### GET latest
GET {{url}}/pastebin?api_key={{api_key}}

### GET specific
GET {{url}}/pastebin/1?api_key={{api_key}}

### DELETE all
DELETE {{url}}/pastebin?api_key={{api_key}}

### DELETE specific
DELETE {{url}}/pastebin/1?api_key={{api_key}}